version: "3.5"

services:
  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.30.0-rc4}
    environment:
      NETWORK:
      CARDANO_NODE_SOCKET_PATH: /ipc/node.socket
    volumes:
      - node-${NETWORK}-db:/data
      - node-ipc:/ipc
      - node-config:/nix/store
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  cardano-submit-api:
    image: inputoutput/cardano-submit-api:${CARDANO_SUBMIT_API_VERSION:-1.30.0-rc4}
    environment:
      NETWORK:
    depends_on:
      - cardano-node
    volumes:
      - node-ipc:/node-ipc
    ports:
      - 8095:8095
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-wallet:
    image: inputoutput/cardano-wallet:2021.9.9
    volumes:
      - wallet-${NETWORK}-db:/wallet-db
      - node-ipc:/ipc
    networks:
      - wallet
    ports:
      - 8090:8090
    entrypoint: []
    command: bash -c "
        ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
        ($$CMD --testnet /config/${NETWORK}/genesis-byron.json)
      "
    environment:
      NETWORK:
      CARDANO_NODE_SOCKET_PATH: /ipc/node.socket
      CMD: "cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  cardano-cli:
    tty: true
    stdin_open: true
    build: docker/cardano-cli
    volumes:
      - node-ipc:/ipc
    networks:
      - wallet
    command: ["echo", "Service cardano-cli disabled"]
    environment:
      NETWORK:
      CARDANO_NODE_SOCKET_PATH: /ipc/node.socket

volumes:
  node-config:
  node-ipc:
  node-alonzo-purple-db:
  node-mainnet-db:
  node-testnet-db:
  wallet-alonzo-purple-db:
  wallet-mainnet-db:
  wallet-testnet-db:

networks:
  wallet:
